=== BobNobrain/expansion/assets/schemas/worldgen/material.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Material",
    "description": "Worldgen material data",
    "type": "object",
    "properties": {
        "$schema": { "type": "string" },
        "id": {
            "title": "ID",
            "description": "Unique material ID",
            "type": "string"
        },
        "tags": {
            "description": "Arbitrary tags",
            "type": "array",
            "items": { "type": "string" }
        },
        "abundance": {
            "description": "How abundant is the material when planets are formed",
            "type": "object",
            "required": [ "min", "max" ],
            "properties": {
                "min": { "type": "number" },
                "max": { "type": "number" }
            }
        },
        "molar": {
            "description": "Molar mass",
            "type": "number",
            "exclusiveMinimum": 0
        },
        "greenhouse": {
            "title": "Greenhouse strength",
            "description": "How strong is `material` in its gaseous form as a greenhouse gas",
            "type": "number",
            "minimum": 0,
            "maximum": 1
        },
        "colors": {
            "type": "object",
            "properties": {
                "solid": { "$ref": "#/$defs/Color" },
                "liquid": { "$ref": "#/$defs/Color" },
                "gas": { "$ref": "#/$defs/Color" }
            }
        },
        "phases": {
            "description": "Phase diagram of the material. Describes its behaviour with respect to temperature and pressure",
            "oneOf": [
                { "$ref": "#/$defs/TriplePointPhaseDiagram" },
                { "$ref": "#/$defs/HePhaseDiagram" },
                { "$ref": "#/$defs/MeltPhaseDiagram" }
            ]
        }
    },
    "required": [ "id", "abundance", "phases", "colors" ],
    "additionalProperties": false,

    "$defs": {
        "Color": {
            "type": "object",
            "properties": {
                "r": { "type": "number", "minimum": 0, "maximum": 1 },
                "g": { "type": "number", "minimum": 0, "maximum": 1 },
                "b": { "type": "number", "minimum": 0, "maximum": 1 },
                "a": { "type": "number", "minimum": 0, "maximum": 1 }
            },
            "required": [ "r", "g", "b" ],
            "editorHints": {
                "kinds": [ "color" ]
            }
        },
        "TriplePointPhaseDiagram": {
            "type": "object",
            "properties": {
                "type": { "const": "triple" },
                "triple": { "$ref": "#/$defs/PhaseDiagramPoint" },
                "subl": { "$ref": "#/$defs/PhaseDiagramLine" },
                "melt": { "$ref": "#/$defs/PhaseDiagramLine" },
                "boil": { "$ref": "#/$defs/PhaseDiagramLine" }
            },
            "required": [ "type", "triple", "subl", "melt", "boil" ],
            "editorHints": {
                "component": "expansion.phys.phased"
            }
        },
        "HePhaseDiagram": {
            "type": "object",
            "properties": {
                "type": { "const": "he" },
                "melt": { "$ref": "#/$defs/PhaseDiagramLine" },
                "boil": { "$ref": "#/$defs/PhaseDiagramLine" }
            },
            "required": [ "type", "melt", "boil" ],
            "editorHints": {
                "component": "expansion.phys.phased"
            }
        },
        "MeltPhaseDiagram": {
            "type": "object",
            "properties": {
                "type": { "const": "melt" },
                "melt": { "$ref": "#/$defs/PhaseDiagramLine" }
            },
            "required": [ "type", "melt" ],
            "editorHints": {
                "component": "expansion.phys.phased"
            }
        },
        "PhaseDiagramLine": {
            "type": "array",
            "items": { "$ref": "#/$defs/PhaseDiagramPoint" },
            "minItems": 1
        },
        "PhaseDiagramPoint": {
            "type": "object",
            "properties": {
                "P": { "type": "number", "minimum": 0 },
                "T": { "type": "number", "minimum": 0 }
            },
            "required": [ "T", "P" ]
        }
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/o2.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "o2",
    "tags": [
        "wg",
        "volatile"
    ],
    "abundance": {
        "min": 0.0005,
        "max": 0.001
    },
    "molar": 32,
    "greenhouse": 0.1,
    "colors": {
        "solid": {
            "r": 0.7686274509803922,
            "g": 0.9137254901960784,
            "b": 1
        },
        "liquid": {
            "r": 0.7686274509803922,
            "g": 0.9137254901960784,
            "b": 1
        },
        "gas": {
            "r": 0.7686274509803922,
            "g": 0.9137254901960784,
            "b": 1
        }
    },
    "phases": {
        "type": "triple",
        "triple": {
            "P": 152,
            "T": 54.36
        },
        "boil": [
            {
                "P": 5014000,
                "T": 154.78
            }
        ],
        "melt": [
            {
                "P": 10000000000,
                "T": 110
            }
        ],
        "subl": [
            {
                "P": 1,
                "T": 35
            }
        ]
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/co.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "co",
    "tags": [
        "wg",
        "volatile"
    ],
    "abundance": {
        "min": 0.01,
        "max": 0.04
    },
    "molar": 28,
    "greenhouse": 0.5,
    "colors": {
        "solid": {
            "r": 1,
            "g": 1,
            "b": 1
        },
        "liquid": {
            "r": 1,
            "g": 1,
            "b": 1
        },
        "gas": {
            "r": 1,
            "g": 1,
            "b": 1
        }
    },
    "phases": {
        "type": "triple",
        "triple": {
            "P": 15370,
            "T": 67.65
        },
        "boil": [
            {
                "P": 3452900,
                "T": 132.91
            }
        ],
        "melt": [
            {
                "P": 10000000000,
                "T": 110
            }
        ],
        "subl": [
            {
                "P": 1,
                "T": 10
            }
        ]
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/silicate.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "silicate",
    "tags": [
        "wg"
    ],
    "abundance": {
        "min": 0.9,
        "max": 0.99
    },
    "molar": 60,
    "colors": {
        "solid": {
            "r": 0.9372549019607843,
            "g": 0.9019607843137255,
            "b": 0.7490196078431373
        },
        "liquid": {
            "r": 0.9372549019607843,
            "g": 0.9019607843137255,
            "b": 0.7490196078431373
        },
        "gas": {
            "r": 0.9372549019607843,
            "g": 0.9019607843137255,
            "b": 0.7490196078431373
        }
    },
    "phases": {
        "type": "melt",
        "melt": [
            {
                "P": 100000,
                "T": 1200
            }
        ]
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/h2o.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "h2o",
    "tags": [ "wg" ],
    "abundance": { "min": 0.2, "max": 0.6 },
    "molar": 18,
    "greenhouse": 0.5,
    "colors": {
        "solid": { "r": 0.4, "g": 0.8, "b": 1 },
        "liquid": { "r": 0.1, "g": 0.4, "b": 1 },
        "gas": { "r": 0.9, "g": 0.9, "b": 0.9 }
    },
    "phases": {
        "type": "triple",
        "triple": { "P": 611.657, "T": 273.16 },
        "subl": [ { "P": 0, "T": 213 }, { "P": 10, "T": 223 }, { "P": 100, "T": 250 } ],
        "melt": [ { "P": 1e7, "T": 273 }, { "P": 5e8, "T": 248 }, { "P": 1e9, "T": 280 }, { "P": 5e9, "T": 350 }, { "P": 1e10, "T": 670 } ],
        "boil": [ { "P": 1e5, "T": 373.15 }, { "P": 22.064e6, "T": 647 } ]
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/no2.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "no2",
    "tags": [
        "wg",
        "volatile",
        "toxic"
    ],
    "abundance": {
        "min": 0.001,
        "max": 0.002
    },
    "molar": 46,
    "colors": {
        "solid": {
            "r": 0.9529411764705882,
            "g": 0.9529411764705882,
            "b": 0.9529411764705882
        },
        "liquid": {
            "r": 0.8156862745098039,
            "g": 0.6274509803921569,
            "b": 0.24313725490196078
        },
        "gas": {
            "r": 0.7137254901960784,
            "g": 0.41568627450980394,
            "b": 0.09803921568627451
        }
    },
    "phases": {
        "type": "triple",
        "triple": {
            "P": 187289,
            "T": 261.9
        },
        "boil": [
            {
                "P": 10132500,
                "T": 431.15
            }
        ],
        "melt": [
            {
                "P": 10000000000,
                "T": 300
            }
        ],
        "subl": [
            {
                "P": 1,
                "T": 150
            }
        ]
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/basalt.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "basalt",
    "tags": [ "wg" ],
    "abundance": { "min": 0.9, "max": 0.99 },
    "molar": 200,
    "colors": {
        "solid": { "r": 0.4, "g": 0.4, "b": 0.5 },
        "liquid": { "r": 0.4, "g": 0.4, "b": 0.5 },
        "gas": { "r": 0.4, "g": 0.4, "b": 0.5 }
    },
    "phases": {
        "type": "melt",
        "melt": [ { "P": 1e5, "T": 1200 } ]
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/he.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "he4",
    "tags": [ "wg" ],
    "abundance": { "min": 0.1, "max": 0.2 },
    "molar": 4,
    "colors": {
        "solid": { "r": 1, "g": 1, "b": 1 },
        "liquid": { "r": 1, "g": 1, "b": 1, "a": 0.1 },
        "gas": { "r": 1, "g": 1, "b": 1, "a": 0 }
    },
    "phases": {
        "type": "he",
        "melt": [ { "P": 2e6, "T": 0 }, { "P": 3e6, "T": 1.7 }, { "P": 6e6, "T": 3.5 } ],
        "boil": [ { "P": 0, "T": 1.8 }, { "P": 5073, "T": 2.17 }, { "P": 229e3, "T": 5.2 } ]
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/h2.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "h2",
    "tags": [ "wg", "volatile" ],
    "abundance": { "min": 0.2, "max": 0.4 },
    "molar": 2,
    "colors": {
        "solid": { "r": 1, "g": 1, "b": 1 },
        "liquid": { "r": 1, "g": 1, "b": 1, "a": 0.1 },
        "gas": { "r": 1, "g": 1, "b": 1, "a": 0 }
    },
    "phases": {
        "type": "triple",
        "triple": { "P": 7042, "T": 13.81 },
        "subl": [ { "P": 0, "T": 0.5 } ],
        "melt": [ { "P": 10e5, "T": 12 }, { "P": 20e5, "T": 20 }, { "P": 1e8, "T": 100 }, { "P": 1e10, "T": 1000 } ],
        "boil": [ { "P": 13e5, "T": 33.15 } ]
    }
}
