=== BobNobrain/expansion/assets/schemas/worldgen/material.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Material",
    "description": "Worldgen material data",
    "type": "object",
    "properties": {
        "$schema": { "type": "string" },
        "id": {
            "title": "ID",
            "description": "Unique material ID",
            "type": "string"
        },
        "tags": {
            "description": "Arbitrary tags",
            "type": "array",
            "items": { "type": "string" }
        },
        "abundance": {
            "description": "How abundant is the material when planets are formed",
            "type": "object",
            "required": [ "min", "max" ],
            "properties": {
                "min": { "type": "number" },
                "max": { "type": "number" }
            }
        },
        "molar": {
            "description": "Molar mass",
            "type": "number",
            "exclusiveMinimum": 0
        },
        "greenhouse": {
            "title": "Greenhouse strength",
            "description": "How strong is `material` in its gaseous form as a greenhouse gas",
            "type": "number",
            "minimum": 0,
            "maximum": 1
        },
        "colors": {
            "type": "object",
            "properties": {
                "solid": { "$ref": "#/$defs/Color" },
                "liquid": { "$ref": "#/$defs/Color" },
                "gas": { "$ref": "#/$defs/Color" }
            }
        },
        "phases": {
            "description": "Phase diagram of the material. Describes its behaviour with respect to temperature and pressure",
            "oneOf": [
                { "$ref": "#/$defs/TriplePointPhaseDiagram" },
                { "$ref": "#/$defs/HePhaseDiagram" },
                { "$ref": "#/$defs/MeltPhaseDiagram" }
            ]
        }
    },
    "required": [ "id", "abundance", "phases", "colors" ],
    "additionalProperties": false,

    "$defs": {
        "Color": {
            "type": "object",
            "properties": {
                "r": { "type": "number", "minimum": 0, "maximum": 1 },
                "g": { "type": "number", "minimum": 0, "maximum": 1 },
                "b": { "type": "number", "minimum": 0, "maximum": 1 },
                "a": { "type": "number", "minimum": 0, "maximum": 1 }
            },
            "required": [ "r", "g", "b" ],
            "editorHints": {
                "kinds": [ "color" ]
            }
        },
        "TriplePointPhaseDiagram": {
            "type": "object",
            "properties": {
                "type": { "const": "triple" },
                "triple": { "$ref": "#/$defs/PhaseDiagramPoint" },
                "subl": { "$ref": "#/$defs/PhaseDiagramLine" },
                "melt": { "$ref": "#/$defs/PhaseDiagramLine" },
                "boil": { "$ref": "#/$defs/PhaseDiagramLine" }
            },
            "required": [ "type", "triple", "subl", "melt", "boil" ],
            "editorHints": {
                "component": "expansion.phys.phased"
            }
        },
        "HePhaseDiagram": {
            "type": "object",
            "properties": {
                "type": { "const": "he" },
                "melt": { "$ref": "#/$defs/PhaseDiagramLine" },
                "boil": { "$ref": "#/$defs/PhaseDiagramLine" }
            },
            "required": [ "type", "melt", "boil" ],
            "editorHints": {
                "component": "expansion.phys.phased"
            }
        },
        "MeltPhaseDiagram": {
            "type": "object",
            "properties": {
                "type": { "const": "melt" },
                "melt": { "$ref": "#/$defs/PhaseDiagramLine" }
            },
            "required": [ "type", "melt" ],
            "editorHints": {
                "component": "expansion.phys.phased"
            }
        },
        "PhaseDiagramLine": {
            "type": "array",
            "items": { "$ref": "#/$defs/PhaseDiagramPoint" },
            "minItems": 1
        },
        "PhaseDiagramPoint": {
            "type": "object",
            "properties": {
                "P": { "type": "number", "minimum": 0 },
                "T": { "type": "number", "minimum": 0 }
            },
            "required": [ "T", "P" ]
        }
    }
}

=== BobNobrain/expansion/assets/worldgen/materials/co2.json
{
    "$schema": "../../schemas/worldgen/material.json",
    "id": "co2",
    "tags": [
        "wg",
        "volatile"
    ],
    "abundance": {
        "min": 0.05,
        "max": 0.1
    },
    "molar": 44,
    "greenhouse": 0.6,
    "colors": {
        "solid": {
            "r": 0.8274509803921568,
            "g": 0.8431372549019608,
            "b": 0.8117647058823529
        },
        "liquid": {
            "r": 0.8274509803921568,
            "g": 0.8431372549019608,
            "b": 0.8117647058823529
        },
        "gas": {
            "r": 0.8274509803921568,
            "g": 0.8431372549019608,
            "b": 0.8117647058823529
        }
    },
    "phases": {
        "type": "triple",
        "triple": {
            "P": 517770,
            "T": 216.58
        },
        "boil": [
            {
                "P": 7375450,
                "T": 304.13
            }
        ],
        "melt": [
            {
                "P": 10000000000,
                "T": 235
            }
        ],
        "subl": [
            {
                "P": 4,
                "T": 0
            }
        ]
    }
}
